---
title: "Descriptives Experiment"
subtitle: "Open code and supplementary material to: Lateral Reading Germany"
format:
  html:
    code-fold: true
editor: visual
knitr:
  opts_chunk: 
    warning: false
    message: false
---

```{r}
library(readr)
library(tidyverse)
library(gridExtra)
library(PupillometryR)
library(purrr)

data <- read_delim("../data/exp_data.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
data[data == 997] <- NA 

data <- data%>%
  drop_na(source_trustworthiness)

#### Binary Percentage Barplots
ratings_percentages_ST <- data %>%
  mutate(item = ifelse(item_type > 0, "True items", "False items"),
    trustworthy = ifelse(source_trustworthiness > 0, "trustworthy", "untrustworthy"),
    treatment = recode_factor(treatment, `control` = "C", `lateral_reading` = "LR", `online_search` = "OS")) %>%
  group_by(phase, item, treatment, trustworthy) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(phase, item, treatment) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  select(-count)%>%
  rename(rating = trustworthy)%>%
  na.omit()

ratings_percentages_ST_pre <- data %>%
  filter(phase == "pre")%>%
  mutate(item = ifelse(item_type > 0, "True items", "False items"),
    trustworthy = ifelse(source_trustworthiness > 0, "trustworthy", "untrustworthy"),
    treatment = recode_factor(treatment, `control` = "C", `lateral_reading` = "LR", `online_search` = "OS")) %>%
  group_by(phase, item, treatment, trustworthy) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(phase, item, treatment) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  select(-count)%>%
  rename(rating = trustworthy)%>%
  na.omit()

ratings_percentages_CC <- data %>%
  mutate(item = ifelse(item_type > 0, "True items", "False items"),
         credible = ifelse(claim_credibility > 0, "credible", "not_credible"),
         treatment = recode_factor(treatment, `control` = "C", `lateral_reading` = "LR", `online_search` = "OS")) %>%
  group_by(phase, item, treatment, credible) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(phase, item, treatment) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  select(-count)%>%
  rename(rating = credible)%>%
  na.omit()

ratings_percentages_CC_pre <- data %>%
  filter(phase == "pre")%>%
  mutate(item = ifelse(item_type > 0, "True items", "False items"),
         credible = ifelse(claim_credibility > 0, "credible", "not_credible"),
         treatment = recode_factor(treatment, `control` = "C", `lateral_reading` = "LR", `online_search` = "OS")) %>%
  group_by(phase, item, treatment, credible) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(phase, item, treatment) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  select(-count)%>%
  rename(rating = credible)%>%
  na.omit()
```

### Percentages of correct ratings

```{r}
perc_plot_ST <- ggplot(ratings_percentages_ST) +
  geom_bar(aes(y = percentage, x = interaction(treatment), fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "Percentage (%)", fill = "Rating") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("trustworthy" = "#1b998b", "untrustworthy" = "#d7263d")) +
  ggtitle("Source Trustworthiness Ratings", subtitle = "Binary split of 4-point rating scale") +
  guides(fill = "none") +
  facet_grid(phase ~ item,space = 'free_x', scales = 'free_x', switch = 'x')+
  theme(panel.grid.minor.x = element_blank()) + 
  theme(panel.spacing.x = unit(0,"line")) +
  theme(strip.placement = 'outside',
        strip.background.x = element_blank())

perc_plot_CC <- ggplot(ratings_percentages_CC) +
  geom_bar(aes(y = percentage, x = interaction(treatment), fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "Percentage (%)", fill = "Rating") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("credible" = "#1b998b", "not_credible" = "#d7263d")) +
  ggtitle("Claim Credibility Ratings", subtitle = "Binary split of 4-point rating scale") +
  facet_grid(phase ~ item,space = 'free_x', scales = 'free_x', switch = 'x')+
  theme(panel.grid.minor.x = element_blank()) + 
  theme(panel.spacing.x = unit(0,"line")) +
  theme(strip.placement = 'outside',
        strip.background.x = element_blank())

```

### Aggregated over waves

```{r}
perc_plot_ST_s <- ggplot(ratings_percentages_ST) +
  geom_bar(aes(y = percentage, x = interaction(treatment), fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "Percentage (%)", fill = "Rating") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("trustworthy" = "#1b998b", "untrustworthy" = "#d7263d")) +
  ggtitle("Source Trustworthiness Ratings") +
  guides(fill = "none") +
  facet_grid(. ~ item,space = 'free_x', scales = 'free_x', switch = 'x')+
  theme(panel.grid.minor.x = element_blank()) + 
  theme(panel.spacing.x = unit(0,"line")) +
  theme(strip.placement = 'outside',
        strip.background.x = element_blank())

perc_plot_CC_s <- ggplot(ratings_percentages_CC) +
  geom_bar(aes(y = percentage, x = interaction(treatment), fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "", fill = "Rating") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("credible" = "#1b998b", "not_credible" = "#d7263d")) +
  ggtitle("Claim Credibility Ratings") +
  facet_grid(. ~ item,space = 'free_x', scales = 'free_x', switch = 'x')+
  theme(panel.grid.minor.x = element_blank()) + 
  theme(panel.spacing.x = unit(0,"line")) +
  theme(strip.placement = 'outside',
        strip.background.x = element_blank())

combi_percs_s <- grid.arrange(perc_plot_ST_s, perc_plot_CC_s, nrow = 1,widths=c(5,7),
                              bottom = "Binary splits of 4-point rating scales; ratings aggregated over waves.")

```

### Aggregated over time points and groups

```{r}
perc_plot_ST_simple <- ggplot(ratings_percentages_ST) +
  geom_bar(aes(y = percentage, x = item, fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "Percentage (%)", fill = "Rating") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("trustworthy" = "#1b998b", "untrustworthy" = "#d7263d")) +
  ggtitle("Source Trustworthiness")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

perc_plot_CC_simple <- ggplot(ratings_percentages_CC) +
  geom_bar(aes(y = percentage, x = item, fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "Percentage (%)", fill = "Rating") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("credible" = "#1b998b", "not_credible" = "#d7263d"),
                    labels = c("credible" = "credible", "not_credible" = "not credible")) +
  ggtitle("Claim Credibility")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

combi_percs_simple <- grid.arrange(perc_plot_CC_simple,perc_plot_ST_simple, nrow = 2)

```

### Pre-treatment only

```{r}
perc_plot_ST_simple_pre <- ggplot(ratings_percentages_ST_pre) +
  geom_bar(aes(y = percentage, x = item, fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "Percentage (%)", fill = "Rating (pre-treatment)") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("trustworthy" = "#1b998b", "untrustworthy" = "#d7263d"),
                    labels = c("trustworthy" = "Trustworthy", "untrustworthy" = "Untrustworthy")) +
  ggtitle("Source trustworthiness")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ratings_percentages_ST_pre%>%
  group_by(item,rating)%>%
  summarize(percentage = mean(percentage))

perc_plot_CC_simple_pre <- ggplot(ratings_percentages_CC_pre) +
  geom_bar(aes(y = percentage, x = item, fill = rating), 
           stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "", y = "Percentage (%)", fill = "Rating (pre-treatment)") +
  theme_bw(base_size = 12) +
  scale_fill_manual(values = c("credible" = "#1b998b", "not_credible" = "#d7263d"),
                    labels = c("credible" = "Credible", "not_credible" = "Not credible")) +
  ggtitle("Claim credibility")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ratings_percentages_CC_pre%>%
  group_by(item,rating)%>%
  summarize(percentage = mean(percentage))

combi_percs_simple_pre <- grid.arrange(perc_plot_CC_simple_pre,perc_plot_ST_simple_pre, nrow = 2)

```

##### Simple rating means / raw data

```{r}
# means with SDs and SEs
ratings_means <- data%>%
  mutate(item = ifelse(item_type > 0, "true", "false"))%>%
  group_by(phase,item,treatment)%>%
  summarise(ST_mean = mean(source_trustworthiness, na.rm=T),
            CC_mean = mean(claim_credibility, na.rm=T),
            ST_se = sd(source_trustworthiness, na.rm=T)/sqrt(n()),
            CC_se = sd(claim_credibility, na.rm=T)/sqrt(n()),
            ST_sd = sd(source_trustworthiness, na.rm=T),
            CC_se = sd(claim_credibility, na.rm=T))%>%
  na.omit()

# means with bootstrapped CIs
rating_means_boot_ST <- data%>%
  mutate(item = ifelse(item_type > 0, "true", "false"))%>%
  group_by(phase,item,treatment)%>%
  do(data.frame(rbind(Hmisc::smean.cl.boot(.$source_trustworthiness,conf.int=.95, B=1000))))%>%
  na.omit()
rating_means_boot_CC <- data%>%
  mutate(item = ifelse(item_type > 0, "true", "false"))%>%
  group_by(phase,item,treatment)%>%
  do(data.frame(rbind(Hmisc::smean.cl.boot(.$claim_credibility,conf.int=.95, B=1000))))%>%
  na.omit()

data$phase <- factor(data$phase, levels = c("pre", "post", "follow-up"))
rating_means_boot_ST$phase <- factor(rating_means_boot_ST$phase, levels = c("pre", "post", "follow-up"))
rating_means_boot_CC$phase <- factor(rating_means_boot_CC$phase, levels = c("pre", "post", "follow-up"))
```

### Plotting Means

```{r}
# Pre-Post-Follow-up Trustworthy
source1 <- rating_means_boot_ST%>%
  ggplot()+
  geom_point(aes(y = Mean, x = phase, group = item, color = item), size = 2)+
  geom_hline(yintercept = 0, linetype="dashed", colour = "black") + 
  geom_errorbar(aes(x = phase, ymin = Lower, ymax = Upper, group = item, color = item), 
                width = 0.1) +
  labs(color = "Item Type", x = "", y = "Trustworthiness Rating")+
  scale_color_manual(values = c("#d7263d", "#1b998b"))+
  ggtitle("Average Source Trustworthiness Ratings", subtitle = "Mean ratings with bootstrapped 95% CIs")+
  scale_y_continuous(breaks = c(1.5, 0.5, -0.5, -1.5),labels = c("definitely \n trustworthy", 
                                                                 "probably \n trustworthy",
                                                                 "probably \n not trustworthy",
                                                                 "definitely \n not trustworthy"))+
  facet_grid(. ~ treatment, labeller = as_labeller(c("control" = "Control", 
                                                     "lateral_reading" = "Lateral Reading",
                                                     "online_search" = "Online Search")))+
  theme_bw(base_size = 12)+
  theme(legend.position = "bottom")+
  ylab("")

source1

# Pre-Post-Follow-Up Credibility
claims1 <- rating_means_boot_CC%>%
  ggplot()+
  geom_hline(yintercept = 0, linetype="dashed", colour = "black") + 
  geom_point(aes(y = Mean, x = phase, group = item, color = item), size = 2)+
  geom_errorbar(aes(x = phase, ymin = Lower, ymax = Upper, group = item, color = item), 
                width = 0.1) +
  labs(color = "Item Type", x = "", y = "")+
  scale_color_manual(values = c("#d7263d","#1b998b"))+
  ggtitle("Average Claim Credibility Ratings", subtitle = "Mean ratings with bootstrapped 95% CIs")+
  scale_y_continuous(breaks = c(1.5, 0.5, -0.5, -1.5),labels = c("definitely \n credible", 
                                                                 "probably \n credible",
                                                                 "probably \n not credible",
                                                                 "definitely \n not credible"))+
  facet_grid(. ~ treatment, labeller = as_labeller(c("control" = "Control", 
                                                     "lateral_reading" = "Lateral Reading",
                                                     "online_search" = "Online Search")))+
  theme_bw(base_size = 12)+
  theme(legend.position = "bottom")

claims1
```

### Plot Raw Data

```{r}
agg_source <- data %>%
  filter(!is.na(phase)) %>%
  mutate(item = ifelse(item_type > 0, "trustworthy", "untrustworthy")) %>%
  group_by(phase, source_trustworthiness, item, treatment) %>%
  summarise(count = n(), .groups = "drop")

source1ba <- ggplot(agg_source, aes(x = phase, y = source_trustworthiness, fill = item)) +
  geom_point(aes(size = count, group = item),
             shape = 21, alpha = 0.5, stroke = 0, color = "white",
             position = position_dodge(width = 0.7)) +
  geom_text(aes(label = count, group = item),
            position = position_dodge(width = 0.7),
            color = "white", size = 2, vjust = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed", colour = "black") +
  scale_fill_manual(values = c("untrustworthy" = "#d7263d", "trustworthy" = "#1b998b")) +
  ggtitle("Raw source trustworthiness ratings") +
  geom_point(data = rating_means_boot_ST, aes(y = Mean, color = item), size = 3, shape = 23, 
             fill = "black", stroke = 1,position = position_dodge(width = 0)) +   
  geom_errorbar(data = rating_means_boot_ST, inherit.aes = FALSE,
              aes(x = phase, ymin = Lower, ymax = Upper, group = item), size = 0.5,
              width = 0, color = "black", position = position_dodge(width = 0))+
  scale_y_continuous(breaks = c(1.5, 0.5, -0.5, -1.5),
                     expand = expansion(mult = c(0.1, 0.1)),
                     labels = c("definitely \n trustworthy",
                                "probably \n trustworthy",
                                "probably \n not trustworthy",
                                "definitely \n not trustworthy")) +
  facet_grid(. ~ treatment, labeller = as_labeller(c("control" = "Control",
                                                       "lateral_reading" = "Lateral Reading",
                                                       "online_search" = "Online Search"))) +
  theme_bw(base_size = 11) +
  scale_size_continuous(range = c(5, 10))+
  labs(y = "", x = "",fill = "Source")+
  guides(size = "none", color = "none",
         fill = guide_legend(override.aes = list(size = 5)))+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank())

source1ba

agg_claim <- data %>%
  filter(!is.na(phase)) %>%
  mutate(item = ifelse(item_type > 0, "true", "false")) %>%
  group_by(phase, claim_credibility, item, treatment) %>%
  summarise(count = n(), .groups = "drop")

claims1ba <- ggplot(agg_claim, aes(x = phase, y = claim_credibility, fill = item)) +
  geom_point(aes(size = count, group = item),
             shape = 21, alpha = 0.5, stroke = 0,color = "white",
             position = position_dodge(width = 0.7)) +
  geom_text(aes(label = count, group = item),
            position = position_dodge(width = 0.7),
            color = "white", size = 2, vjust = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed", colour = "black") +
  scale_fill_manual(values = c("false" = "#d7263d", "true" = "#1b998b")) +
  ggtitle("Raw claim credibility ratings") +
  geom_point(data = rating_means_boot_CC, aes(y = Mean, color = item), size = 3, shape = 23, 
             fill = "black", stroke = 1, position = position_dodge(width = 0)) +   
  geom_errorbar(data = rating_means_boot_CC, inherit.aes = FALSE,
              aes(x = phase, ymin = Lower, ymax = Upper, group = item),size = 0.5,
              width = 0, color = "black", position = position_dodge(width = 0))+
  scale_y_continuous(breaks = c(1.5, 0.5, -0.5, -1.5),
                     expand = expansion(mult = c(0.1, 0.1)),
                     labels = c("definitely \n credible",
                                "probably \n credible",
                                "probably \n not credible",
                                "definitely \n not credible")) +
  facet_grid(. ~ treatment, labeller = as_labeller(c("control" = "Control",
                                                       "lateral_reading" = "Lateral reading",
                                                       "online_search" = "Online search"))) +
  theme_bw(base_size = 11) +
  scale_size_continuous(range = c(5, 10))+
  labs(y = "", x = "", fill = "Claim")+
  guides( size = "none", color = "none",
         fill = guide_legend(override.aes = list(size = 5)))+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank())

claims1ba

```
